name: GameManager
version: '${project.version}'
main: gamemanager.gamemanager.GameManager
api-version: '1.19'
depend:
  - DecentHolograms
load-permissions-after: DecentHolograms
commands:
  game:
    usage: /game
  queue:
    usage: /queue
